# Generated by Django 4.1.7 on 2023-04-29 11:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0023_rename_actorfilm_actorchapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorchapter',
            name='Actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actorchapter', to='Entity.actor'),
        ),
        migrations.AlterField(
            model_name='actorchapter',
            name='Chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapteractor', to='Entity.chapter'),
        ),
        migrations.AlterField(
            model_name='history',
            name='Rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
