# Generated by Django 4.1.7 on 2023-04-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0024_alter_actorchapter_actor_alter_actorchapter_chapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserName',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
