# Generated by Django 4.1.7 on 2023-05-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0026_history_historyview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserName',
            field=models.EmailField(max_length=254),
        ),
    ]
