# Generated by Django 4.1.7 on 2023-05-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0027_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserName',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
